spring.application.name=annonces-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/annonces_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

# Cloudinary pour upload des photos
cloudinary.cloud-name=de5gvpuj5
cloudinary.api-key=567314386769151
cloudinary.api-secret=-soiYe_OhXJZsfaDluUEvzKsyrg