spring.application.name=annonces-service
server.port=${PORT:8082}

# Base de données ? lit les variables Railway
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/annonces_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:de5gvpuj5}
cloudinary.api-key=${CLOUDINARY_API_KEY:567314386769151}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:-soiYe_OhXJZsfaDluUEvzKsyrg}

# JWT
app.jwt.secret=${JWT_SECRET:UnSecretTresLongDauMoins32CaracteresObligatoire2026!}
app.jwt.expiration=${JWT_EXPIRATION:86400000}